name: dnstestapi
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  equatable: ^1.0.0
  flutter_bloc: ^3.2.0
  get_it: ^4.0.1
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

